# Generated by Django 5.2.12 on 2026-03-13 16:04

import datetime
import django.db.models.deletion
import web.models.character
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to=web.models.character.photo_upload_to)),
                ('profile', models.TextField(max_length=100000)),
                ('background_image', models.ImageField(upload_to=web.models.character.backgraound_image_upload_to)),
                ('create_time', models.DateTimeField(default=datetime.datetime(2026, 3, 13, 16, 4, 56, 428299, tzinfo=datetime.timezone.utc))),
                ('update_time', models.DateTimeField(default=datetime.datetime(2026, 3, 13, 16, 4, 56, 428299, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.userprofile')),
            ],
        ),
    ]
